version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    prometheus:
      patterns:
      - github.com/prometheus/common
      - github.com/prometheus/client_model
      - github.com/prometheus/client_golang
